# Generated by Django 6.0.7 on 2026-07-20 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('slug', models.SlugField(blank=True, help_text="Généré automatiquement à partir du titre s'il est laissé vide.", max_length=220, unique=True, verbose_name='slug')),
                ('excerpt', models.CharField(blank=True, help_text='Résumé court affiché dans la liste des articles.', max_length=300, verbose_name='accroche')),
                ('content', models.TextField(verbose_name='contenu')),
                ('cover_image', models.URLField(blank=True, help_text="URL de l'image illustrant l'article.", verbose_name='image de couverture')),
                ('is_published', models.BooleanField(default=True, help_text="Un article non publié n'apparaît que pour son auteur.", verbose_name='publié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='articles_ar_created_312397_idx')],
            },
        ),
    ]
